apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-app
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app-container
        image: adwinsky/test
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: DD_TRACE_AGENT_URL
          value: 'unix:///var/run/datadog/apm.socket'
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        volumeMounts:
        - name: apmsocketpath
          mountPath: /var/run/datadog
      volumes:
        - hostPath:
            path: /var/run/datadog/
          name: apmsocketpath